### ISSUE TITLE
5. Integrate the single site key value store into our Raft implementation

### ISSUE THREAD

**Issue by krithikvaidya** [krithikvaidya/distributed-dns#13]
The state machine for our use case of Raft consensus is an instance of a key-value store. Every replica will run the key-value store individually, and when the replica detects entries that are committed to the log, it will apply them to the key-value store too.

Write the code to start up the key value store, while starting up the raft node. The single-site key-value store is present in the single_site_kv_store in the repo root. You may need to copy/modify this implementation (for eg, it runs on port 8080 always. You will need to change this to support user-inputted port number, because we won't be able to have multiple instances of the key value store listening at the same port, on the same machine).

**Comment by rak108** [comment]
I'll take this up
