### ISSUE TITLE
7. Handling client interactions

### ISSUE THREAD

**Issue by krithikvaidya** [krithikvaidya/distributed-dns#15]
In raft, all the operations to be performed on the state machine are handled by the leader.  Write code for user interaction with the leader. The client can perform GET/POST/PUT/DELETE operations (since those are the ones supported https://github.com/krithikvaidya/distributed-dns/tree/main/single_site_kv_store). 

For now, you can assume that the client will never try to interact with a non-leader, and that the client performs operations by inputting them in the leader's terminal. For eg, an operation that the client wishes to perform could be - _GET abcd_ (where abcd is the key). Follow the procedures described in the paper for all operations. For example, for read operations, you can ensure a non-stale read by sending a heartbeat before responding to the client.

**Comment by DeltaCube23** [comment]
I'll do this
