### ISSUE TITLE
Couple of tasks

### ISSUE THREAD

**Issue by krithikvaidya** [krithikvaidya/distributed-dns#22]
- Before answering any of the requests from the client, ensure that all the committed log entries have been applied to the key-value store. This is required to ensure that the client doesn't receive invalid/outdated replies (for example if a client writes a k:v pair and it's committed to the log, but before it's applied to the k:v store they perform a GET request for the same key, the key value store will return invalid key. Similarly you can think of the reasoning of requiring it for the POST, PUT, DELETE requests too).

- There are two HTTP servers in our program (one for listening to client requests and one to interact with the key value store) and their handler functions are defined in _kv_store/restaccess_key_value.go_ and _raft_server.go_. In all the handlers, refine error handling and also return appropriate HTTP codes (200 OK, 201 Created (for eg. for a post request), etc.). You may also need to edit the parts of the code that perform HTTP requests to the key-value store server to accommodate the new changes.

**Comment by rak108** [comment]
I'll take this up
