### ISSUE TITLE
Debug and fix issues related to crashing and reboot of replicas

### ISSUE THREAD

**Issue by krithikvaidya** [krithikvaidya/distributed-dns#23]
In the current state, the system correctly works when no nodes crash. The current implementation accommodates for node(s) crashing, but has bugs which need to be fixed to make it continue functioning properly when node(s) crash. You need to find these bugs, figure out why they're occurring and fix them.

First, you'd probably need to change the initial startup code, keeping in mind that the same code will be executed when the node crashes and comes back online. Assume that the address of the node does not change between crashes. Keep in mind that once a gRPC connection has been established and the client stub has been obtained (like [here](https://github.com/krithikvaidya/distributed-dns/blob/a82530d28a5cf89407a65e7f2b338b8969b1fbca/replicated_kv_store/raft_node.go#L104)) , if the server goes down and comes back up later, the same client stub will still work for making RPCs. When the server is down, calling an RPC with that client object will return an error.

Then, you can manually try to stop node(s), perform some operations with the client (i.e. perform operations to generate more logs), restart the stopped node(s) and see if the logs are correctly updated. In case a leader is stopped, you need to check if the re-election is performed correctly. 

You don't need to rigorously test, if things seem to be fine at a surface level it's enough at this point.

**Comment by DeltaCube23** [comment]
I'll do this.

**Comment by krithikvaidya** [comment]
#26 #29
