### ISSUE TITLE
Serial numbers for every client request, and redirection for requests made to non leaders

### ISSUE THREAD

**Issue by krithikvaidya** [krithikvaidya/distributed-dns#24]
1. In section 8, the Raft paper says - "Our goal for Raft is to implement linearizable semantics (each operation appears to execute instantaneously, exactly once, at some point between its invocation and its response). However, as described so far Raft can execute a command multiple times: for example, if the leader crashes after committing the log entry but before responding to the client, the client will retry the command with a new leader, causing it to be executed a second time. The solution is for clients to assign unique serial numbers to every command. Then, the state machine tracks the latest serial number processed for each client, along with the associated response. If it receives a command whose serial number has already been executed, it responds immediately without re-executing the request.". Think of how this can be practically implemented in our program, discuss it and write code for it.

2. In Raft, the leader is supposed to handle all client requests. In case the client sends a request to a non-leader, it needs to inform the client about the leader's address (the current implementation only responds with an error saying that the node is not the leader).

**Comment by jkk2000** [comment]
Ill take this

**Comment by krithikvaidya** [comment]
#27
