### ISSUE TITLE
Add test: Leader election 3

### ISSUE THREAD

**Issue by suhasks123** [krithikvaidya/distributed-dns#34]
## Overview:
- **(implemented)** Leader election 1 represents the test for the initial leader election `TestInitialElection`.
- **(implemented)** Leader election 2 represents the test `TestReElection` for the re-election of a leader when the current leader crashes.
- **(to implement in this issue)** Leader election 3 represents a situation similar to leader election 2 when the former leader is brought back online.

## Procedure:
- Crash the leader, in such a way that it retains the persistent state information.
- Wait for a new leader to be elected and connect the crashed former leader node back to the system.
- Wait for the leader conflicts to be resolved.
- Check if eventually, the system settles at a single leader state.

**Comment by rak108** [comment]
I'll take this up
