### ISSUE TITLE
Add testing utility to create a network partition

### ISSUE THREAD

**Issue by suhasks123** [krithikvaidya/distributed-dns#38]
## Overview:
- Write a testing utility to create a network partition.

- The simplest version of this can be to partition a **single node** away from the system. Note that this is different from **crashing** the node since the raft process of the node is still running and only the **connections** in the network to the node are destroyed.

- Building on top of this, functionality can be implement to cut **multiple nodes** off from the original system.

**Comment by DeltaCube23** [comment]
i will take this
