### ISSUE TITLE
1. Complete the RequestVote RPC implementation

### ISSUE THREAD

**Issue by krithikvaidya** [krithikvaidya/distributed-dns#5]
The RPC declaration and the protobuf messages it uses has been declared in _replicated_kv_store/protos/replica.proto_. Complete the RPC implementation in the _replicated_kv_store/request_vote.go_ file. The protobuf messages have been defined according to Figure 2 in the paper. If you need to edit the .proto file, you can recompile it using

```protoc --go_out=plugins=grpc:. --go_opt=paths=source_relative replica.proto```

**Comment by rak108** [comment]
I'll take this up
