### ISSUE TITLE
3. Transitioning into a candidate, and from candidate to leader/follower

### ISSUE THREAD

**Issue by krithikvaidya** [krithikvaidya/distributed-dns#7]
When the election timer times out, the follower begins the transition into becoming a candidate. Write code to implement this. Follow the procedure described in the paper for this.  You will need to take care of the different scenarios - eg: if the RequestVote response from another replica has a higher term number.

You will also need to implement the code for transitioning from candidate to leader, and for candidate to follower.

**Comment by DeltaCube23** [comment]
I'll take this up.

**Comment by krithikvaidya** [comment]
Looks fine for now. Only thing that I think would be better if changed is the RunElectionTimer method. I don't think a ticker is required there. I was thinking you could add another channel to the RaftNode struct called something like stopElectionTimer. Golang also has the timeout feature with time.After().  

So in the RunElectionTimer method, you could have a select statement, and the cases in the _select_ statement could look something like - 

case <-time.After(...) {...} // for election timeout, 

case <-node.stopElectionTimer {...} // this channel is written to when the election timer needs to be stopped

case <-node.electionResetEvent {...} // this channel will be written to when the election timeout timer needs to be restarted
                                                          // (You'll need to change the declaration of electionResetEvent in the RaftNode struct too)
